import type { CatalogItemSeed } from "./dhms-catalog-types";

/** Individual tests from DHMS requisition form page 1 — one checkbox per row. */
export const DHMS_CATALOG_ITEMS: CatalogItemSeed[] = [
  // Blood Chemistry
  { code: "ALCOHOL", name: "ALCOHOL", category: "blood_chemistry", specimenHint: "serum", sortOrder: 10 },
  { code: "ALK_PHOS", name: "ALK PHOS", category: "blood_chemistry", specimenHint: "serum", sortOrder: 20 },
  { code: "ALT_SGPT", name: "ALT/SGPT", category: "blood_chemistry", specimenHint: "serum", sortOrder: 30 },
  { code: "AST_SGOT", name: "AST/SGOT", category: "blood_chemistry", specimenHint: "serum", sortOrder: 40 },
  { code: "AMYLASE", name: "AMYLASE", category: "blood_chemistry", specimenHint: "serum", sortOrder: 50 },
  { code: "BILIRUBIN_TOT_DIRECT", name: "BILIRUBIN (TOT & DIRECT)", category: "blood_chemistry", specimenHint: "serum", sortOrder: 60 },
  { code: "CALCIUM", name: "CALCIUM", category: "blood_chemistry", specimenHint: "serum", sortOrder: 70 },
  { code: "CHOLINESTERASE", name: "CHOLINESTERASE", category: "blood_chemistry", specimenHint: "serum", sortOrder: 80 },
  { code: "CREATININE", name: "CREATININE", category: "blood_chemistry", specimenHint: "serum", sortOrder: 90 },
  { code: "HS_CRP", name: "hs CRP", category: "blood_chemistry", specimenHint: "serum", sortOrder: 100 },
  { code: "ELECTROLYTES", name: "ELECTROLYTES", category: "blood_chemistry", specimenHint: "serum", sortOrder: 110 },
  { code: "GGTP", name: "GGTP", category: "blood_chemistry", specimenHint: "serum", sortOrder: 120 },
  { code: "GLUCOSE_FAST", name: "GLUCOSE - FAST", category: "blood_chemistry", specimenHint: "serum", fastingRequired: true, sortOrder: 130 },
  { code: "GLUCOSE_2HR_PP", name: "GLUCOSE - 2hr PP", category: "blood_chemistry", specimenHint: "serum", fastingRequired: true, sortOrder: 140 },
  { code: "GLUCOSE_RAND", name: "GLUCOSE - RAND", category: "blood_chemistry", specimenHint: "serum", sortOrder: 150 },
  { code: "GLUCOSE_OSULLIVAN", name: "GLUCOSE-O'SULLIVAN", category: "blood_chemistry", specimenHint: "serum", sortOrder: 160 },
  { code: "GTT_2_3_4_6HR", name: "GTT - 2 3 4 6 hr (F)", category: "blood_chemistry", specimenHint: "serum", fastingRequired: true, sortOrder: 170 },
  { code: "HBA1C", name: "HBA1C", category: "blood_chemistry", specimenHint: "serum", sortOrder: 180 },
  { code: "LDH", name: "LDH", category: "blood_chemistry", specimenHint: "serum", sortOrder: 190 },
  { code: "LIPASE", name: "LIPASE", category: "blood_chemistry", specimenHint: "serum", sortOrder: 200 },
  { code: "HDL_CHOLESTEROL", name: "HDL CHOLESTEROL (F)", category: "blood_chemistry", specimenHint: "serum", fastingRequired: true, sortOrder: 210 },
  { code: "LDL_CHOLESTEROL", name: "LDL CHOLESTEROL (F)", category: "blood_chemistry", specimenHint: "serum", fastingRequired: true, sortOrder: 220 },
  { code: "TOTAL_CHOLESTEROL", name: "TOTAL CHOLESTEROL", category: "blood_chemistry", specimenHint: "serum", fastingRequired: true, sortOrder: 230 },
  { code: "TRIGLYCERIDE", name: "TRIGLYCERIDE (F)", category: "blood_chemistry", specimenHint: "serum", fastingRequired: true, sortOrder: 240 },
  { code: "LIPO_ELECTROPHORESIS", name: "LIPO ELECTROPHORESIS", category: "blood_chemistry", specimenHint: "serum", fastingRequired: true, sortOrder: 250 },
  { code: "LIPIDS", name: "Lipids", category: "blood_chemistry", specimenHint: "serum", fastingRequired: true, sortOrder: 255 },
  { code: "MAGNESIUM", name: "MAGNESIUM", category: "blood_chemistry", specimenHint: "serum", sortOrder: 260 },
  { code: "PHOSPHORUS", name: "PHOSPHORUS", category: "blood_chemistry", specimenHint: "serum", sortOrder: 270 },
  { code: "PROTEINS", name: "PROTEINS (Alb & Glob)", category: "blood_chemistry", specimenHint: "serum", sortOrder: 280 },
  { code: "A_G", name: "A/G Ratio", category: "blood_chemistry", specimenHint: "serum", sortOrder: 285 },
  { code: "PROTEIN_ELECTROPHORESIS", name: "PROTEIN ELECTROPHORESIS", category: "blood_chemistry", specimenHint: "serum", sortOrder: 290 },
  { code: "UREA_BUN", name: "UREA / BUN", category: "blood_chemistry", specimenHint: "serum", sortOrder: 300 },
  { code: "URIC_ACID", name: "URIC ACID", category: "blood_chemistry", specimenHint: "serum", sortOrder: 310 },

  // Haematology
  { code: "CBC", name: "CBC", category: "haematology", specimenHint: "blood", sortOrder: 10 },
  { code: "ESR", name: "ESR", category: "haematology", specimenHint: "blood", sortOrder: 20 },
  { code: "CROSS_MATCH", name: "CROSS MATCH", category: "haematology", specimenHint: "blood", sortOrder: 30 },
  { code: "GROUP_RH", name: "GROUP & Rh", category: "haematology", specimenHint: "blood", sortOrder: 40 },
  { code: "FIBRINOGEN", name: "FIBRINOGEN", category: "haematology", specimenHint: "blood", sortOrder: 50 },
  { code: "HB_PCV", name: "Hb / PCV", category: "haematology", specimenHint: "blood", sortOrder: 60 },
  { code: "HB", name: "Hb", category: "haematology", specimenHint: "blood", sortOrder: 65 },
  { code: "WBC_DIFF", name: "WBC / Diff", category: "haematology", specimenHint: "blood", sortOrder: 70 },
  { code: "INDICES", name: "INDICES", category: "haematology", specimenHint: "blood", sortOrder: 80 },
  { code: "RBC", name: "RBC", category: "haematology", specimenHint: "blood", sortOrder: 90 },
  { code: "LUPUS_ANTICOAG", name: "LUPUS ANTICOAG.", category: "haematology", specimenHint: "blood", sortOrder: 100 },
  { code: "MONO", name: "MONO", category: "haematology", specimenHint: "blood", sortOrder: 110 },
  { code: "PT_INR", name: "PT / INR", category: "haematology", specimenHint: "blood", sortOrder: 120 },
  { code: "PTT", name: "PTT", category: "haematology", specimenHint: "blood", sortOrder: 130 },
  { code: "PLATELETS", name: "PLATELETS", category: "haematology", specimenHint: "blood", sortOrder: 140 },

  // Endocrinology
  { code: "BHCG_QUANT", name: "BHCG QUANT.", category: "endocrinology", specimenHint: "serum", sortOrder: 10 },
  { code: "BHCG_QUAL", name: "BHCG QUAL.", category: "endocrinology", specimenHint: "serum", sortOrder: 20 },
  { code: "CORTISOL_AM", name: "CORTISOL AM", category: "endocrinology", specimenHint: "serum", sortOrder: 30 },
  { code: "CORTISOL_PM", name: "CORTISOL PM", category: "endocrinology", specimenHint: "serum", sortOrder: 40 },
  { code: "DHEA_S", name: "DHEA-S", category: "endocrinology", specimenHint: "serum", sortOrder: 50 },
  { code: "ESTRADIOL", name: "ESTRADIOL", category: "endocrinology", specimenHint: "serum", sortOrder: 60 },
  { code: "FSH", name: "FSH", category: "endocrinology", specimenHint: "serum", sortOrder: 70 },
  { code: "LH", name: "LH", category: "endocrinology", specimenHint: "serum", sortOrder: 80 },
  { code: "INSULIN_0HR", name: "INSULIN - 0hr", category: "endocrinology", specimenHint: "serum", sortOrder: 90 },
  { code: "INSULIN_1HR", name: "INSULIN - 1hr", category: "endocrinology", specimenHint: "serum", sortOrder: 100 },
  { code: "INSULIN_2HR", name: "INSULIN - 2hr", category: "endocrinology", specimenHint: "serum", sortOrder: 110 },
  { code: "INSULIN_3HR", name: "INSULIN - 3hr", category: "endocrinology", specimenHint: "serum", sortOrder: 120 },
  { code: "PROGESTERONE", name: "PROGESTERONE", category: "endocrinology", specimenHint: "serum", sortOrder: 130 },
  { code: "PROLACTIN", name: "PROLACTIN", category: "endocrinology", specimenHint: "serum", sortOrder: 140 },
  { code: "PSA_TOTAL", name: "PSA TOTAL", category: "endocrinology", specimenHint: "serum", sortOrder: 150 },
  { code: "PSA_FREE", name: "PSA Free", category: "endocrinology", specimenHint: "serum", sortOrder: 160 },
  { code: "HS_TSH", name: "hs - TSH", category: "endocrinology", specimenHint: "serum", sortOrder: 170 },
  { code: "TSH", name: "TSH", category: "endocrinology", specimenHint: "serum", sortOrder: 175 },
  { code: "T3_TOTAL", name: "T3 Total", category: "endocrinology", specimenHint: "serum", sortOrder: 180 },
  { code: "T3_FREE", name: "T3 Free", category: "endocrinology", specimenHint: "serum", sortOrder: 190 },
  { code: "T3_UPTAKE", name: "T3 Uptake", category: "endocrinology", specimenHint: "serum", sortOrder: 195 },
  { code: "T4_TOTAL", name: "T4 Total", category: "endocrinology", specimenHint: "serum", sortOrder: 200 },
  { code: "T4_FREE", name: "T4 Free", category: "endocrinology", specimenHint: "serum", sortOrder: 210 },
  { code: "TESTOSTERONE", name: "TESTOSTERONE", category: "endocrinology", specimenHint: "serum", sortOrder: 220 },
  { code: "TESTOSTERONE_FREE", name: "TESTOSTERONE Free", category: "endocrinology", specimenHint: "serum", sortOrder: 230 },

  // Urine Chemistry
  { code: "5SHIAA_24HR", name: "5SHIAA - 24hr", category: "urine_chemistry", specimenHint: "urine", sortOrder: 10 },
  { code: "17_KGS_24HR", name: "17 KGs - 24 hr", category: "urine_chemistry", specimenHint: "urine", sortOrder: 20 },
  { code: "17_KS_24HR", name: "17 Ks - 24 hr", category: "urine_chemistry", specimenHint: "urine", sortOrder: 30 },
  { code: "AMYLASE_URINE", name: "AMYLASE", category: "urine_chemistry", specimenHint: "urine", sortOrder: 40 },
  { code: "CALCIUM_URINE_24HR", name: "CALCIUM - 24 hr", category: "urine_chemistry", specimenHint: "urine", sortOrder: 50 },
  { code: "CREATININE_URINE_24HR", name: "CREATININE - 24 hr", category: "urine_chemistry", specimenHint: "urine", sortOrder: 60 },
  { code: "CREATININE_URINE_SPOT", name: "CREATININE - spot", category: "urine_chemistry", specimenHint: "urine", sortOrder: 70 },
  { code: "CREATININE_CLEARANCE_24HR", name: "CREATININE CLEAR - 24 hr", category: "urine_chemistry", specimenHint: "urine", sortOrder: 80 },
  { code: "MICROALBUMIN_24HR", name: "MICROALBUMIN 24 hr", category: "urine_chemistry", specimenHint: "urine", sortOrder: 90 },
  { code: "MICROALBUMIN_CREAT_RATIO", name: "MICROALBUMIN/CREAT RATIO", category: "urine_chemistry", specimenHint: "urine", sortOrder: 100 },
  { code: "PHOSPHORUS_URINE_24HR", name: "PHOSPHORUS - 24 hr", category: "urine_chemistry", specimenHint: "urine", sortOrder: 110 },
  { code: "PREG_TEST_BHCG", name: "PREG TEST (BHCG)", category: "urine_chemistry", specimenHint: "urine", sortOrder: 120 },
  { code: "PROTEIN_URINE_24HR", name: "PROTEIN 24hr", category: "urine_chemistry", specimenHint: "urine", sortOrder: 130 },
  { code: "PROTEIN_URINE_SPOT", name: "PROTEIN - spot", category: "urine_chemistry", specimenHint: "urine", sortOrder: 140 },
  { code: "URINALYSIS_COMPLETE", name: "URINALYSIS - COMPLETE", category: "urine_chemistry", specimenHint: "urine", sortOrder: 150 },
  { code: "VMA_24HR", name: "VMA - 24 hr", category: "urine_chemistry", specimenHint: "urine", sortOrder: 160 },

  // Immunology
  { code: "ANA", name: "ANA", category: "immunology", specimenHint: "serum", sortOrder: 10 },
  { code: "ANTI_DNA", name: "Anti-DNA", category: "immunology", specimenHint: "serum", sortOrder: 20 },
  { code: "ASLO", name: "ASLO", category: "immunology", specimenHint: "serum", sortOrder: 30 },
  { code: "ASTO", name: "ASTO", category: "immunology", specimenHint: "serum", sortOrder: 40 },
  { code: "RA", name: "RA", category: "immunology", specimenHint: "serum", sortOrder: 50 },
  { code: "C3", name: "C3", category: "immunology", specimenHint: "serum", sortOrder: 60 },
  { code: "C4", name: "C4", category: "immunology", specimenHint: "serum", sortOrder: 70 },
  { code: "CRP", name: "CRP", category: "immunology", specimenHint: "serum", sortOrder: 80 },
  { code: "CMV_IGG", name: "CMV IgG", category: "immunology", specimenHint: "serum", sortOrder: 90 },
  { code: "CMV_IGM", name: "CMV IgM", category: "immunology", specimenHint: "serum", sortOrder: 100 },
  { code: "DENGUE_IGM", name: "DENGUE IgM", category: "immunology", specimenHint: "serum", sortOrder: 110 },
  { code: "DENGUE_IGG", name: "DENGUE IgG", category: "immunology", specimenHint: "serum", sortOrder: 120 },
  { code: "FEBRILE_AGGLUTININS", name: "FEBRILE AGGLUTININS", category: "immunology", specimenHint: "serum", sortOrder: 130 },
  { code: "HAV_IGM", name: "HAV IgM", category: "immunology", specimenHint: "serum", sortOrder: 140 },
  { code: "HB_CORE_AB", name: "HB Core Ab", category: "immunology", specimenHint: "serum", sortOrder: 150 },
  { code: "HBEAG", name: "HBeAg", category: "immunology", specimenHint: "serum", sortOrder: 160 },
  { code: "HBSAB", name: "HBsAb", category: "immunology", specimenHint: "serum", sortOrder: 170 },
  { code: "HBSAG", name: "HBsAg", category: "immunology", specimenHint: "serum", sortOrder: 180 },
  { code: "HCVAB", name: "HCVAb", category: "immunology", specimenHint: "serum", sortOrder: 190 },
  { code: "HERPES_I_IGM", name: "HERPES I IgM", category: "immunology", specimenHint: "serum", sortOrder: 200 },
  { code: "HERPES_I_IGG", name: "HERPES I IgG", category: "immunology", specimenHint: "serum", sortOrder: 210 },
  { code: "HERPES_II_IGM", name: "HERPES II IgM", category: "immunology", specimenHint: "serum", sortOrder: 220 },
  { code: "HERPES_II_IGG", name: "HERPES II IgG", category: "immunology", specimenHint: "serum", sortOrder: 230 },
  { code: "HTLV_I_II", name: "HTLV I/II", category: "immunology", specimenHint: "serum", sortOrder: 240 },
  { code: "HIV_1_2", name: "HIV 1/II", category: "immunology", specimenHint: "serum", sortOrder: 250 },
  { code: "HIV_CONFIRM", name: "HIV Confirmation", category: "immunology", specimenHint: "serum", sortOrder: 255 },
  { code: "RUBELLA_IGM", name: "RUBELLA IgM", category: "immunology", specimenHint: "serum", sortOrder: 260 },
  { code: "RUBELLA_IGG", name: "RUBELLA IgG", category: "immunology", specimenHint: "serum", sortOrder: 270 },
  { code: "TOXOPLASMA_IGM", name: "TOXOPLASMA IgM", category: "immunology", specimenHint: "serum", sortOrder: 280 },
  { code: "TOXOPLASMA_IGG", name: "TOXOPLASMA IgG", category: "immunology", specimenHint: "serum", sortOrder: 290 },
  { code: "VDRL", name: "VDRL", category: "immunology", specimenHint: "serum", sortOrder: 300 },
  { code: "MHA_TP", name: "MHA - TP", category: "immunology", specimenHint: "serum", sortOrder: 310 },
  { code: "WIDAL", name: "WIDAL", category: "immunology", specimenHint: "serum", sortOrder: 320 },

  // Anaemia
  { code: "B12_FOLATE", name: "B 12 & FOLATE (F)", category: "anaemia", specimenHint: "serum", fastingRequired: true, sortOrder: 10 },
  { code: "COOMBS_DCT", name: "COOMBS - DCT", category: "anaemia", specimenHint: "blood", sortOrder: 20 },
  { code: "COOMBS_ICT", name: "COOMBS - ICT", category: "anaemia", specimenHint: "blood", sortOrder: 30 },
  { code: "FERRITIN", name: "FERRITIN", category: "anaemia", specimenHint: "serum", sortOrder: 40 },
  { code: "G6PD", name: "G6PD", category: "anaemia", specimenHint: "blood", sortOrder: 50 },
  { code: "HB_ELECTROPHORESIS", name: "Hb ELECTROPHORESIS", category: "anaemia", specimenHint: "blood", sortOrder: 60 },
  { code: "IRON_TIBC_SATURATION", name: "IRON / TIBC / SATURATION", category: "anaemia", specimenHint: "serum", sortOrder: 70 },
  { code: "RETICULOCYTE", name: "RETICULOCYTE", category: "anaemia", specimenHint: "blood", sortOrder: 80 },
  { code: "SICKLE_TEST", name: "SICKLE TEST", category: "anaemia", specimenHint: "blood", sortOrder: 90 },

  // Special Chemistry
  { code: "BLOOD_LEAD", name: "BLOOD LEAD", category: "special_chemistry", specimenHint: "blood", sortOrder: 10 },
  { code: "CEA", name: "CEA", category: "special_chemistry", specimenHint: "serum", sortOrder: 20 },
  { code: "CA_125", name: "CA-125", category: "special_chemistry", specimenHint: "serum", sortOrder: 30 },

  // Cardiac Enzymes
  { code: "AST_SGOT_CARDIAC", name: "AST/SGOT", category: "cardiac_enzymes", specimenHint: "serum", sortOrder: 10 },
  { code: "CK_MB", name: "CK-MB", category: "cardiac_enzymes", specimenHint: "serum", sortOrder: 20 },
  { code: "CPK_TOTAL", name: "CPK-TOTAL", category: "cardiac_enzymes", specimenHint: "serum", sortOrder: 30 },
  { code: "LDH_CARDIAC", name: "LDH", category: "cardiac_enzymes", specimenHint: "serum", sortOrder: 40 },
  { code: "TROPONIN_I_QUAL", name: "TROPONIN I - QUAL", category: "cardiac_enzymes", specimenHint: "serum", sortOrder: 50 },
  { code: "TROPONIN_I_QUANT", name: "TROPONIN I - QUANT", category: "cardiac_enzymes", specimenHint: "serum", sortOrder: 60 },
  { code: "TROPONIN_I", name: "TROPONIN I", category: "cardiac_enzymes", specimenHint: "serum", sortOrder: 65 },

  // Bacteriology
  { code: "AFB_SMEAR_CULTURE", name: "AFB - SMEAR & CULTURE", category: "bacteriology", sortOrder: 10 },
  { code: "CHLAMYDIA", name: "CHLAMYDIA", category: "bacteriology", sortOrder: 20 },
  { code: "CULT_SENS_ROUTINE", name: "CULT & SENS: ROUTINE", category: "bacteriology", sortOrder: 30 },
  { code: "CULT_SENS_FUNGAL", name: "CULT & SENS: FUNGAL", category: "bacteriology", sortOrder: 40 },
  { code: "GRAM_SMEAR", name: "GRAM SMEAR", category: "bacteriology", sortOrder: 50 },
  { code: "WET_PREP", name: "WET PREP", category: "bacteriology", sortOrder: 60 },
  { code: "SPECIMEN", name: "SPECIMEN", category: "bacteriology", sortOrder: 70 },

  // Faeces / Miscellaneous
  { code: "AMOEBA", name: "AMOEBA", category: "faeces_misc", sortOrder: 10 },
  { code: "OCCULT_BLOOD", name: "OCCULT BLOOD", category: "faeces_misc", sortOrder: 20 },
  { code: "OVA_PARASITES", name: "OVA & PARASITES", category: "faeces_misc", sortOrder: 30 },
  { code: "PAP_SMEAR", name: "PAP SMEAR", category: "faeces_misc", sortOrder: 40 },
  { code: "SEMEN_ANALYSIS", name: "SEMEN ANALYSIS", category: "faeces_misc", sortOrder: 50 },
  { code: "STONE_ANALYSIS", name: "STONE ANALYSIS", category: "faeces_misc", sortOrder: 60 },

  // Drugs of Abuse
  { code: "DOA_ALCOHOL_BLOOD", name: "ALCOHOL - B", category: "drugs_of_abuse", specimenHint: "blood", sortOrder: 10 },
  { code: "DOA_ALCOHOL_URINE", name: "ALCOHOL - U", category: "drugs_of_abuse", specimenHint: "urine", sortOrder: 20 },
  { code: "AMPHETAMINE_U", name: "AMPHETAMINE (U)", category: "drugs_of_abuse", specimenHint: "urine", sortOrder: 30 },
  { code: "CANNABIS_U", name: "CANNABIS (U)", category: "drugs_of_abuse", specimenHint: "urine", sortOrder: 40 },
  { code: "COCAINE_U", name: "COCAINE (U)", category: "drugs_of_abuse", specimenHint: "urine", sortOrder: 50 },
  { code: "OPIATES_U", name: "OPIATES (U)", category: "drugs_of_abuse", specimenHint: "urine", sortOrder: 60 },
  { code: "DOA_OTHER", name: "OTHER", category: "drugs_of_abuse", sortOrder: 70 },

  // Therapeutic Drug
  { code: "DILANTIN_PHENYTOIN", name: "DILANTIN / PHENYTOIN", category: "therapeutic_drug", specimenHint: "serum", sortOrder: 10 },
  { code: "LITHIUM", name: "LITHIUM", category: "therapeutic_drug", specimenHint: "serum", sortOrder: 20 },
  { code: "PHENOBARBITAL", name: "PHENOBARBITAL", category: "therapeutic_drug", specimenHint: "serum", sortOrder: 30 },
  { code: "SALICYLATES", name: "SALICYLATES", category: "therapeutic_drug", specimenHint: "serum", sortOrder: 40 },
  { code: "TEGRETOL_CARBAMAZEPINE", name: "TEGRETOL / CARBAMAZEPINE", category: "therapeutic_drug", specimenHint: "serum", sortOrder: 50 },
  { code: "VALPROIC_ACID", name: "VALPROIC ACID", category: "therapeutic_drug", specimenHint: "serum", sortOrder: 60 },
  { code: "THERAPEUTIC_OTHER", name: "OTHER", category: "therapeutic_drug", specimenHint: "serum", sortOrder: 70 },
];
