export {
  DRAX_HALL_ROUTING_SETTINGS,
  ROUTING_PRESET_CONSOLIDATED_DHMS,
  ROUTING_PRESET_GRANULAR,
  groupTestsByDepartment,
  normalizeLabRoutingSettings,
  resolveRoutingDepartment,
  resolveRoutingDepartmentByKey,
  routingDepartmentSortIndex,
  routingDepartmentsForUi,
  type DepartmentLabelGroup,
  type LabRoutingSettings,
  type ResolvedRoutingDepartment,
  type RoutingDepartmentDef,
  type RoutingMode,
} from "./routing-departments";
