packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  "@serialport/bindings-cpp": true
  esbuild: true
  prisma: true

autoInstallPeers: true
strictPeerDependencies: false
confirmModulesPurge: false
