/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabRouteImport } from './routes/_lab'
import { Route as LabBenchRouteImport } from './routes/_lab/bench'
import { Route as LabRegisterRouteImport } from './routes/_lab/register'
import { Route as LabSyncRouteImport } from './routes/_lab/sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/_lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LabBenchRoute = LabBenchRouteImport.update({
  id: '/bench',
  path: '/bench',
  getParentRoute: () => LabRoute,
} as any)
const LabRegisterRoute = LabRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LabRoute,
} as any)
const LabSyncRoute = LabSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => LabRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bench': typeof LabBenchRoute
  '/register': typeof LabRegisterRoute
  '/sync': typeof LabSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bench': typeof LabBenchRoute
  '/register': typeof LabRegisterRoute
  '/sync': typeof LabSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_lab': typeof LabRouteWithChildren
  '/_lab/bench': typeof LabBenchRoute
  '/_lab/register': typeof LabRegisterRoute
  '/_lab/sync': typeof LabSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bench' | '/register' | '/sync'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bench' | '/register' | '/sync'
  id:
    '__root__' | '/' | '/_lab' | '/_lab/bench' | '/_lab/register' | '/_lab/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LabRoute: typeof LabRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_lab': {
      id: '/_lab'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_lab/bench': {
      id: '/_lab/bench'
      path: '/bench'
      fullPath: '/bench'
      preLoaderRoute: typeof LabBenchRouteImport
      parentRoute: typeof LabRoute
    }
    '/_lab/register': {
      id: '/_lab/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof LabRegisterRouteImport
      parentRoute: typeof LabRoute
    }
    '/_lab/sync': {
      id: '/_lab/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof LabSyncRouteImport
      parentRoute: typeof LabRoute
    }
  }
}

interface LabRouteChildren {
  LabBenchRoute: typeof LabBenchRoute
  LabRegisterRoute: typeof LabRegisterRoute
  LabSyncRoute: typeof LabSyncRoute
}

const LabRouteChildren: LabRouteChildren = {
  LabBenchRoute: LabBenchRoute,
  LabRegisterRoute: LabRegisterRoute,
  LabSyncRoute: LabSyncRoute,
}

const LabRouteWithChildren = LabRoute._addFileChildren(LabRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LabRoute: LabRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
