/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabRouteImport } from './routes/_lab'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LabBenchRouteImport } from './routes/_lab/bench'
import { Route as LabLabelsRouteImport } from './routes/_lab/labels'
import { Route as LabPatientsRouteImport } from './routes/_lab/patients'
import { Route as LabProfileRouteImport } from './routes/_lab/profile'
import { Route as LabRegisterRouteImport } from './routes/_lab/register'
import { Route as LabReleaseRouteImport } from './routes/_lab/release'
import { Route as LabSyncRouteImport } from './routes/_lab/sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/_lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LabBenchRoute = LabBenchRouteImport.update({
  id: '/bench',
  path: '/bench',
  getParentRoute: () => LabRoute,
} as any)
const LabLabelsRoute = LabLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => LabRoute,
} as any)
const LabPatientsRoute = LabPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => LabRoute,
} as any)
const LabProfileRoute = LabProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LabRoute,
} as any)
const LabRegisterRoute = LabRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LabRoute,
} as any)
const LabReleaseRoute = LabReleaseRouteImport.update({
  id: '/release',
  path: '/release',
  getParentRoute: () => LabRoute,
} as any)
const LabSyncRoute = LabSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => LabRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bench': typeof LabBenchRoute
  '/labels': typeof LabLabelsRoute
  '/patients': typeof LabPatientsRoute
  '/profile': typeof LabProfileRoute
  '/register': typeof LabRegisterRoute
  '/release': typeof LabReleaseRoute
  '/sync': typeof LabSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bench': typeof LabBenchRoute
  '/labels': typeof LabLabelsRoute
  '/patients': typeof LabPatientsRoute
  '/profile': typeof LabProfileRoute
  '/register': typeof LabRegisterRoute
  '/release': typeof LabReleaseRoute
  '/sync': typeof LabSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_lab': typeof LabRouteWithChildren
  '/login': typeof LoginRoute
  '/_lab/bench': typeof LabBenchRoute
  '/_lab/labels': typeof LabLabelsRoute
  '/_lab/patients': typeof LabPatientsRoute
  '/_lab/profile': typeof LabProfileRoute
  '/_lab/register': typeof LabRegisterRoute
  '/_lab/release': typeof LabReleaseRoute
  '/_lab/sync': typeof LabSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bench'
    | '/labels'
    | '/patients'
    | '/profile'
    | '/register'
    | '/release'
    | '/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/bench'
    | '/labels'
    | '/patients'
    | '/profile'
    | '/register'
    | '/release'
    | '/sync'
  id:
    | '__root__'
    | '/'
    | '/_lab'
    | '/login'
    | '/_lab/bench'
    | '/_lab/labels'
    | '/_lab/patients'
    | '/_lab/profile'
    | '/_lab/register'
    | '/_lab/release'
    | '/_lab/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LabRoute: typeof LabRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_lab': {
      id: '/_lab'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_lab/bench': {
      id: '/_lab/bench'
      path: '/bench'
      fullPath: '/bench'
      preLoaderRoute: typeof LabBenchRouteImport
      parentRoute: typeof LabRoute
    }
    '/_lab/labels': {
      id: '/_lab/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof LabLabelsRouteImport
      parentRoute: typeof LabRoute
    }
    '/_lab/patients': {
      id: '/_lab/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof LabPatientsRouteImport
      parentRoute: typeof LabRoute
    }
    '/_lab/profile': {
      id: '/_lab/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LabProfileRouteImport
      parentRoute: typeof LabRoute
    }
    '/_lab/register': {
      id: '/_lab/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof LabRegisterRouteImport
      parentRoute: typeof LabRoute
    }
    '/_lab/release': {
      id: '/_lab/release'
      path: '/release'
      fullPath: '/release'
      preLoaderRoute: typeof LabReleaseRouteImport
      parentRoute: typeof LabRoute
    }
    '/_lab/sync': {
      id: '/_lab/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof LabSyncRouteImport
      parentRoute: typeof LabRoute
    }
  }
}

interface LabRouteChildren {
  LabBenchRoute: typeof LabBenchRoute
  LabLabelsRoute: typeof LabLabelsRoute
  LabPatientsRoute: typeof LabPatientsRoute
  LabProfileRoute: typeof LabProfileRoute
  LabRegisterRoute: typeof LabRegisterRoute
  LabReleaseRoute: typeof LabReleaseRoute
  LabSyncRoute: typeof LabSyncRoute
}

const LabRouteChildren: LabRouteChildren = {
  LabBenchRoute: LabBenchRoute,
  LabLabelsRoute: LabLabelsRoute,
  LabPatientsRoute: LabPatientsRoute,
  LabProfileRoute: LabProfileRoute,
  LabRegisterRoute: LabRegisterRoute,
  LabReleaseRoute: LabReleaseRoute,
  LabSyncRoute: LabSyncRoute,
}

const LabRouteWithChildren = LabRoute._addFileChildren(LabRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LabRoute: LabRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
